#!/usr/bin/env bash
set -e

# ai-dev-framework v3 — Global installation
# Usage: ./scripts/install.sh

FRAMEWORK_DIR="$(cd "$(dirname "$0")/.." && pwd)"
GREEN='\033[0;32m'; BLUE='\033[0;34m'; YELLOW='\033[1;33m'; NC='\033[0m'
log()  { echo -e "${BLUE}[ai-dev-framework v3]${NC} $1"; }
ok()   { echo -e "${GREEN}[ok]${NC} $1"; }
warn() { echo -e "${YELLOW}[warn]${NC} $1"; }

log "Installing ai-dev-framework v3 globally..."

mkdir -p ~/.claude/agents ~/.claude/skills ~/.claude/hooks

# Agents
cp "$FRAMEWORK_DIR/agents/"*.md ~/.claude/agents/
ok "13 agents installed in ~/.claude/agents/"

# Skills
cp -r "$FRAMEWORK_DIR/skills/." ~/.claude/skills/
ok "Skills installed in ~/.claude/skills/"

# Hooks
cp "$FRAMEWORK_DIR/hooks/hooks.json" ~/.claude/hooks/hooks.json
mkdir -p ~/.claude/hooks/scripts
cp "$FRAMEWORK_DIR/hooks/scripts/"*.js ~/.claude/hooks/scripts/ 2>/dev/null || true
chmod +x ~/.claude/hooks/scripts/*.js 2>/dev/null || true
ok "Hooks installed in ~/.claude/hooks/"

# Global settings.json
if [ ! -f ~/.claude/settings.json ]; then
  cat > ~/.claude/settings.json << 'SETTINGS'
{
  "model": "sonnet",
  "env": {
    "MAX_THINKING_TOKENS": "10000",
    "CLAUDE_AUTOCOMPACT_PCT_OVERRIDE": "50",
    "CLAUDE_CODE_SUBAGENT_MODEL": "haiku"
  }
}
SETTINGS
  ok "settings.json created in ~/.claude/"
fi

# ─── Create global `ai-framework` command ─────────────────────────────────────
# Writes a small wrapper script to ~/.local/bin/ai-framework so the user
# can run `ai-framework init`, `ai-framework update` from anywhere,
# regardless of where they cloned the repo.

mkdir -p ~/.local/bin

cat > ~/.local/bin/ai-framework << WRAPPER
#!/usr/bin/env bash
# ai-dev-framework CLI wrapper — auto-generated by install.sh
# Do not edit. Re-run install.sh to regenerate.
FRAMEWORK_DIR="$FRAMEWORK_DIR"

case "\$1" in
  init)
    shift
    exec bash "\$FRAMEWORK_DIR/scripts/init-project.sh" "\$@"
    ;;
  update)
    exec bash "\$FRAMEWORK_DIR/scripts/update.sh"
    ;;
  install)
    exec bash "\$FRAMEWORK_DIR/scripts/install.sh"
    ;;
  *)
    echo "Usage: ai-framework <command> [options]"
    echo ""
    echo "Commands:"
    echo "  init [template]   Initialize the framework in the current project"
    echo "                    Templates: saas | api-backend | fullstack-web | ai-app"
    echo "  update            Update the framework to the latest version"
    echo "  install           Re-run global installation"
    echo ""
    echo "Examples:"
    echo "  ai-framework init saas"
    echo "  ai-framework init"
    echo "  ai-framework update"
    ;;
esac
WRAPPER

chmod +x ~/.local/bin/ai-framework

# Add ~/.local/bin to PATH if not already there
SHELL_RC=""
if [ -f "$HOME/.zshrc" ]; then
  SHELL_RC="$HOME/.zshrc"
elif [ -f "$HOME/.bashrc" ]; then
  SHELL_RC="$HOME/.bashrc"
fi

if [ -n "$SHELL_RC" ]; then
  if ! grep -q 'export PATH="$HOME/.local/bin:$PATH"' "$SHELL_RC" 2>/dev/null; then
    echo '' >> "$SHELL_RC"
    echo '# ai-dev-framework' >> "$SHELL_RC"
    echo 'export PATH="$HOME/.local/bin:$PATH"' >> "$SHELL_RC"
    ok "PATH updated in $SHELL_RC"
  fi
fi

# Also export for current session
export PATH="$HOME/.local/bin:$PATH"

ok "Global command created: ai-framework"

# ─── Reload shell config for current session ──────────────────────────────────
# So the user doesn't have to manually source their shell config.
if [ -f "$HOME/.zshrc" ]; then
  source "$HOME/.zshrc" 2>/dev/null || true
elif [ -f "$HOME/.bashrc" ]; then
  source "$HOME/.bashrc" 2>/dev/null || true
fi

# ─── Summary ──────────────────────────────────────────────────────────────────

echo ""
ok "Installation complete."
echo ""
echo "Use from anywhere:"
echo "  ai-framework init saas     → new project"
echo "  ai-framework init          → existing project"
echo "  ai-framework update        → update the framework"
echo ""
echo "Next steps:"
echo "  cd your-project && ai-framework init"
echo "  claude"
echo "  /new-project  or  /analyze-project"